server.port=8443
server.ssl.enabled=true
server.ssl.protocol=TLS
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=123456
server.ssl.key-alias=book
server.ssl.key-password=123456

server.servlet.session.timeout=1800
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax

spring.security.oauth2.client.registration.google.client-id=1085192165319-cltaqqsrfht9nf2p1mbh2s4c7tgke7um.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline
spring.security.oauth2.client.provider.google.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

#spring.datasource.url=jdbc:h2:file:c:\h2-databases\bookdb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.web.resources.add-mappings=false

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.sql.init.data-locations=classpath:/sql/sql.sql
spring.sql.init.mode=always

spring.messages.basename=messages
spring.messages.cache-duration=3600
spring.messages.encoding=UTF-8

spring.messages.default-locale=en

spring.mvc.favicon.enabled=false

jwt.secret=A8d!xPzQm2#LvR6sT@wZ9NcYbG3JpV7K
jwt.expiration-ms=86400
jwt.issuer=BookstoreApp

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
